name: First Actions Demo

on:
    workflow_dispatch

jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo Hello ${{ github.ref }}


    Print-Log-File:
        runs-on: ubuntu-latest
        steps:
            - name: Print Log text file
              run: cat ./log.txt