name: First Actions Demo

on:
    workflow_dispatch

jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo Hello ${{ github.ref }}


    Print-Log-File:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Print Log text file
              run: cat log.txt

    Print-Log-Using-ShellScript:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Change file permissions
              run: chmod +x first.sh
            - name: Print Log text file using shell script
              run: |
                echo "Running shell script for log extraction"
                ./first.sh log.txt